### ISSUE TITLE
multiple definition of 'testCases_metadata'

### ISSUE THREAD

**Issue by dib130030** [fredericbonnet/picotest#2]
```
main.c:
#include "picotest.h"
PICOTEST_SUITE(mainSuite, testCases)
...

testcases.c:
#include "picotest.h"
PICOTEST_SUITE(testCases, testcase)
...
```

Because 
`_PICOTEST_SUITE_DECLARE_SUBTEST(_testName)`
in picotest.h does not declare
`PicoTestMetadata _PICOTEST_METADATA(_testName)`
as 'extern' a PicoTestMetadata struct is created in each .obj file, which leads to conflict.

v.1.3.0 builds without error.

**Comment by fredericbonnet** [comment]
That's strange, I can't reproduce this behavior. What compiler are you using? Mine is the MSVC build tools on Windows, I've also tried the latest GCC on Linux and besides a few minor warnings (which I will fix in the next version) it works fine. Here are my sources:

`main.c`:
```c
#include "picotest.h"
PICOTEST_SUITE(mainSuite, testCases);

void main() {
    mainSuite(NULL);
}
```

`testcases.c`:
```c
#include <stdio.h>

#include "picotest.h"
PICOTEST_SUITE(testCases, testcase);

PICOTEST_CASE(testcase) {
    printf("testcase\n");
    PICOTEST_ASSERT(0);
}
```

**Comment by fredericbonnet** [comment]
Even though I couldn't reproduce the problem, you're right about `PicoTestMetadata` needing an `extern` declaration. The new release 1.41. hopefully fixes this problem, can you confirm that it works on your side?

**Comment by dib130030** [comment]
I am using MSys64/MinGW-w64 on Windows with CLion. Release 1.41 fixes the issue, thanks! It also fixes
```warning: initialization of 'const struct PicoTestMetadata **' from incompatible pointer type 'PicoTestMetadata **' [-Wincompatible-pointer-types]```
in PICOTEST_SUITE.
